name: Daily News

on:
  schedule:
    - cron: '15 0  * * *'   # 06:00 NPT
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    environment: GEMINI_API_KEY  # add this line

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run App
        run: mvn spring-boot:run -q -Dspring-boot.run.arguments="--spring.main.web-application-type=none"